steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -f
      - deployment/Dockerfile
      - -t
      - $_IMAGE
      - .
    timeout: 3600s

images:
  - $_IMAGE

timeout: 3600s
